"""oauth_integrations

Revision ID: 76fe726a71a8
Revises: 5d2fbb0a9c01
Create Date: 2026-05-13 22:52:11.707537+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '76fe726a71a8'
down_revision: str | None = '5d2fbb0a9c01'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_integrations',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('account_email', sa.String(length=240), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_oauth_integrations_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_integrations')),
    sa.UniqueConstraint('org_id', 'provider', name='uq_oauth_integrations_org_provider')
    )
    op.create_index(op.f('ix_oauth_integrations_org_id'), 'oauth_integrations', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_oauth_integrations_org_id'), table_name='oauth_integrations')
    op.drop_table('oauth_integrations')
    # ### end Alembic commands ###
