"""initial schema

Revision ID: 2f6cb462b384
Revises: 
Create Date: 2026-05-11 07:36:20.412736+00:00

"""
from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '2f6cb462b384'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs')),
    sa.UniqueConstraint('slug', name=op.f('uq_orgs_slug'))
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('published_version_id', sa.String(length=48), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_agents_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_version_id'], ['agent_versions.id'], name='fk_agents_published_version', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_org_id'), 'agents', ['org_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_api_keys_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_knowledge_bases_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_bases'))
    )
    op.create_index(op.f('ix_knowledge_bases_org_id'), 'knowledge_bases', ['org_id'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('server_url', sa.String(length=512), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('params_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_tools_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tools')),
    sa.UniqueConstraint('org_id', 'name', name='uq_tools_org_name')
    )
    op.create_index(op.f('ix_tools_org_id'), 'tools', ['org_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_users_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('webhook_outbox',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('event', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_webhook_outbox_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_outbox'))
    )
    op.create_index(op.f('ix_webhook_outbox_org_id'), 'webhook_outbox', ['org_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('agent_id', sa.String(length=48), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('env', sa.String(length=20), nullable=False),
    sa.Column('first_message', sa.Text(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=80), nullable=False),
    sa.Column('voice_id', sa.String(length=80), nullable=False),
    sa.Column('stt_id', sa.String(length=80), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('interruption_sensitivity', sa.Float(), nullable=False),
    sa.Column('vad_silence_ms', sa.Integer(), nullable=False),
    sa.Column('flow_graph', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_base_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('server_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_versions_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent_id', 'version', name='uq_agent_version')
    )
    op.create_index(op.f('ix_agent_versions_agent_id'), 'agent_versions', ['agent_id'], unique=False)
    op.create_table('kb_sources',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('kb_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_kb_sources_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_sources'))
    )
    op.create_index(op.f('ix_kb_sources_kb_id'), 'kb_sources', ['kb_id'], unique=False)
    op.create_table('phone_numbers',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('e164', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_resource_id', sa.String(length=120), nullable=True),
    sa.Column('agent_id', sa.String(length=48), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_phone_numbers_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_phone_numbers_org_id_orgs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone_numbers')),
    sa.UniqueConstraint('e164', name=op.f('uq_phone_numbers_e164'))
    )
    op.create_index(op.f('ix_phone_numbers_org_id'), 'phone_numbers', ['org_id'], unique=False)
    op.create_table('squads',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('root_agent_id', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_squads_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_agent_id'], ['agents.id'], name=op.f('fk_squads_root_agent_id_agents'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squads'))
    )
    op.create_index(op.f('ix_squads_org_id'), 'squads', ['org_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('org_id', sa.String(length=48), nullable=False),
    sa.Column('agent_id', sa.String(length=48), nullable=False),
    sa.Column('agent_version_id', sa.String(length=48), nullable=True),
    sa.Column('phone_number_id', sa.String(length=48), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('from_number', sa.String(length=32), nullable=True),
    sa.Column('to_number', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('recording_s3_key', sa.String(length=512), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dynamic_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider_call_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_calls_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_calls_agent_version_id_agent_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_calls_org_id_orgs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], name=op.f('fk_calls_phone_number_id_phone_numbers'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calls'))
    )
    op.create_index(op.f('ix_calls_org_id'), 'calls', ['org_id'], unique=False)
    op.create_index(op.f('ix_calls_provider_call_id'), 'calls', ['provider_call_id'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('kb_id', sa.String(length=48), nullable=False),
    sa.Column('source_id', sa.String(length=48), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name=op.f('fk_kb_chunks_kb_id_knowledge_bases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['kb_sources.id'], name=op.f('fk_kb_chunks_source_id_kb_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_chunks'))
    )
    op.create_index('ix_kb_chunks_embedding_ivfflat', 'kb_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index(op.f('ix_kb_chunks_kb_id'), 'kb_chunks', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_chunks_source_id'), 'kb_chunks', ['source_id'], unique=False)
    op.create_table('squad_edges',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('squad_id', sa.String(length=48), nullable=False),
    sa.Column('from_agent_id', sa.String(length=48), nullable=False),
    sa.Column('to_agent_id', sa.String(length=48), nullable=False),
    sa.Column('context_policy', sa.String(length=16), nullable=False),
    sa.Column('context_n', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_agent_id'], ['agents.id'], name=op.f('fk_squad_edges_from_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], name=op.f('fk_squad_edges_squad_id_squads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_agent_id'], ['agents.id'], name=op.f('fk_squad_edges_to_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_squad_edges'))
    )
    op.create_index(op.f('ix_squad_edges_squad_id'), 'squad_edges', ['squad_id'], unique=False)
    op.create_table('call_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('call_id', sa.String(length=48), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], name=op.f('fk_call_events_call_id_calls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_events'))
    )
    op.create_index(op.f('ix_call_events_call_id'), 'call_events', ['call_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_events_call_id'), table_name='call_events')
    op.drop_table('call_events')
    op.drop_index(op.f('ix_squad_edges_squad_id'), table_name='squad_edges')
    op.drop_table('squad_edges')
    op.drop_index(op.f('ix_kb_chunks_source_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_kb_id'), table_name='kb_chunks')
    op.drop_index('ix_kb_chunks_embedding_ivfflat', table_name='kb_chunks', postgresql_using='ivfflat')
    op.drop_table('kb_chunks')
    op.drop_index(op.f('ix_calls_provider_call_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_org_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_squads_org_id'), table_name='squads')
    op.drop_table('squads')
    op.drop_index(op.f('ix_phone_numbers_org_id'), table_name='phone_numbers')
    op.drop_table('phone_numbers')
    op.drop_index(op.f('ix_kb_sources_kb_id'), table_name='kb_sources')
    op.drop_table('kb_sources')
    op.drop_index(op.f('ix_agent_versions_agent_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_webhook_outbox_org_id'), table_name='webhook_outbox')
    op.drop_table('webhook_outbox')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tools_org_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_knowledge_bases_org_id'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_agents_org_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('orgs')
    # ### end Alembic commands ###
